///// defines the enumerators for the assumption category and risk level /////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AssumptionChecker.Contracts
{
    // == Enumerators for the assumption excluding risk level == //
    public enum AssumptionCategory
    {
        UserContext,       // Assumptions related to the user's context, such as their background, preferences, or environment
        DomainContext,     // Assumptions related to the specific domain or industry relevant to the analysis
        Constraints,       // Assumptions related to constraints or limitations that may impact the analysis or solution
        OutputFormat,      // Assumptions related to the expected format or structure of the output generated by the model
        Ambiguity,         // Assumptions related to ambiguous or unclear aspects of the input or problem statement
        Other              // Any other assumptions that do not fit into the above categories
    }

    // == Enumerators for the risk level of the assumption == //
    public enum RiskLevel
    {
        Low,    // Assumptions that are unlikely to cause significant issues if they turn out to be false
        Medium, // Assumptions that could cause moderate issues if they turn out to be false, but are not critical to the overall success of the solution
        High    // Assumptions that could cause significant issues or even failure of the solution if they turn out to be false
    }
}
